Tildes y typos arreglados en el post
maorar/hyperblog pull request #1
Opened 2020-09-11 21:15 UTC by maorar

No debimos pasar este error a master.

2020-09-11 21:20 UTC, maorar reviewed
En vez de usar tildes directas, usa entidades HTML

2020-09-12 00:40 UTC, APGit-moa requested changes
NO usar tildes sino html entities

2020-09-12 00:44 UTC, APGit-moa requested changes
Necisto cambios

2020-09-12 00:50 UTC, APGit-moa requested changes
Quiero cambios

2020-09-12 00:52 UTC, APGit-moa reviewed
comment

2020-09-12 01:01 UTC, maorar commented
Cambios hechos hazme el merge

2020-09-12 01:05 UTC, APGit-moa approved these changes
Excelente eso era

2020-09-12 01:09 UTC, merged